### ISSUE TITLE
bug(infra): make API deploy symlink cleanup BusyBox-compatible

### ISSUE THREAD

**Issue by ClaudeWorkspace2026** [NoAccountNeeded-Lab/WivWav#977]
## Context

CI run 32231628178 for PR #976 and the matching `main` run 32229754466 both fail `Docker build (api)` in `docker/api/Dockerfile`. The API image uses `node:26-alpine`, whose BusyBox `find` does not implement GNU `-xtype`; the deploy stage exits with `find: unrecognized: -xtype` while cleaning dangling production-dependency symlinks. The command was introduced with the #969 API deployment changes.

## Problem / Goal

Make the API production-dependency cleanup in `docker/api/Dockerfile` portable to Alpine/BusyBox while preserving its intent: delete only dangling symlinks after explicit build-tool packages are removed, retain valid runtime links, and complete the sharp runtime smoke check.

## Proposed approach

- Replace the GNU-only `find ... -xtype l -delete` expression in `docker/api/Dockerfile` with a BusyBox-compatible broken-symlink predicate.
- Keep the worker and scraper Dockerfiles unchanged because they build on Debian and are not failing this CI path.
- Validate the API Docker image through the same target used by CI and confirm valid runtime symlinks and `sharp` still load.

## Acceptance Criteria

- [ ] The API Docker build no longer invokes unsupported BusyBox `find -xtype` and completes successfully from the Alpine builder/deploy stages.
- [ ] The replacement removes dangling symlinks without deleting valid production dependency links, demonstrated by a bounded shell regression check or equivalent Docker-build assertion.
- [ ] The existing API deploy-stage checks still reject forbidden build/test tooling and the `sharp` runtime smoke check still succeeds.
- [ ] The repository API Docker build command and relevant affected checks pass, and the failing CI signature from runs 32231628178 and 32229754466 is absent.

## Notes

This is a baseline CI regression and is not caused by #976's web-test changes. Keep the fix separate from #419 so that PR remains issue-scoped.

**Comment by ClaudeWorkspace2026** [comment]
🤖 **orchestrator[0]** · `run-sprint` · 2026-08-19

Sprint worker starting. Branch: fix/issue-977-make-api-deploy-symlink-cleanup-busybox-compatible · Worktree: /Users/matt/Projects/NoAccountNeeded-Lab/WivWav/.claude/worktrees/issue-977-buginfra-make-api-deploy-symlink-cleanup-busybox-c · Sprint: run-sprint/2026-08-19T08:31

**Comment by ClaudeWorkspace2026** [comment]
🤖 **worker[1]** · `run-sprint` · 2026-08-19

Review roles: reviewer, QA, performance.
Verdict: REVISION_NEEDED: yes → findings fixed → REVISION_NEEDED: no.
Fixed finding count: 2 (API image size budget; incomplete Prisma CLI-only pruning/evidence scope).
Final hosted evidence: API Docker build passed at 441 MB against the 514 MB budget; forbidden-content inspection and sharp smoke passed.

**Comment by ClaudeWorkspace2026** [comment]
Sprint completed successfully. Draft PR: https://github.com/NoAccountNeeded-Lab/WivWav/pull/978 · Commit: `2fdc0ca91d4962b98756a850b19f238a618adc43` · Sprint: `run-sprint/2026-08-19T08:31`.
